import json
import io
import csv
import re
from datetime import datetime, timezone
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status, UploadFile, File, Form, Body
from fastapi.responses import FileResponse, HTMLResponse, StreamingResponse
from fastapi import Query
from sqlalchemy import or_, exc
from sqlalchemy.orm import Session
from .. import models, schemas
from ..database import get_db
from ..core import UPLOAD_DIR, TEMP_UPLOAD_DIR, record_audit_log, require_permission, user_has_permission
from ..auth_jwt import get_current_user, decode_access_token
import uuid
import time
from urllib.parse import quote
import hashlib
import mimetypes
import os
import qrcode
import secrets
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

router = APIRouter(prefix="/documents", tags=["documents"])

QR_IMAGE_DIR = os.path.join(UPLOAD_DIR, "qr")

# bulk registration settings
ALLOWED_EXTENSIONS = {".pdf", ".doc", ".docx"}
ALLOWED_MIME_TYPES = {"application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
MAX_FILE_SIZE = 25 * 1024 * 1024  # 25 MB per file


def _is_allowed_file(filename: str, content_type: str | None) -> tuple[bool, list[str]]:
    errors: list[str] = []
    if not filename:
        errors.append("Missing filename")
        return False, errors
    name = os.path.basename(filename)
    _, ext = os.path.splitext(name.lower())
    if ext not in ALLOWED_EXTENSIONS:
        errors.append("Unsupported file extension")
    if content_type and content_type not in ALLOWED_MIME_TYPES:
        # don't treat mime mismatch as fatal if extension is correct, but warn
        errors.append("Unexpected MIME type")
    return (len(errors) == 0), errors


@router.put("/uploads/tmp/{tmp_name}")
async def upload_tmp_file(tmp_name: str, request: Request, token: str | None = Query(default=None), upload_token: str | None = Query(default=None), db: Session = Depends(get_db)):
    """Accept raw PUT uploads from the browser FilePicker.upload() into TEMP_UPLOAD_DIR.
    The `tmp_name` should be a safe basename generated by the client.
    """
    # Authentication flows supported:
    # 1) Standard JWT in Authorization header -> identify user and require permission
    # 2) upload_token query parameter -> must match a server-created upload metadata file that ties the tmp_name to a specific user
    # 3) BACKEND_AUTH_TOKEN is retained only as an optional dev fallback (not recommended)
    auth_user = None
    env_token = os.getenv("BACKEND_AUTH_TOKEN")
    provided_token = token or request.query_params.get("token")
    provided_upload_token = upload_token or request.query_params.get("upload_token")

    # First, try upload_token path (pre-signed per-user upload)
    try:
        if provided_upload_token:
            # read metadata file for tmp_name
            safe_name = os.path.basename(tmp_name)
            meta_path = os.path.join(TEMP_UPLOAD_DIR, f"{safe_name}.meta.json")
            if not os.path.exists(meta_path):
                raise HTTPException(status_code=401, detail="Upload token invalid or expired")
            try:
                with open(meta_path, "r", encoding="utf-8") as mf:
                    meta = json.load(mf)
            except Exception:
                raise HTTPException(status_code=401, detail="Upload token invalid")
            # verify token and expiry
            if meta.get("upload_token") != provided_upload_token:
                raise HTTPException(status_code=401, detail="Upload token mismatch")
            expires_at = meta.get("expires_at", 0)
            if time.time() > expires_at:
                raise HTTPException(status_code=401, detail="Upload token expired")
            if meta.get("consumed_at"):
                raise HTTPException(status_code=401, detail="Upload token already used")
            # find the user by username stored in meta
            username = meta.get("username")
            if username:
                auth_user = db.query(models.User).filter(models.User.username == username).first()
            if not auth_user:
                raise HTTPException(status_code=401, detail="Upload token user not found")
            # enforce permission for resolved user
            require_permission(auth_user, "register_documents")
        else:
            # fallback to Authorization/JWT path
            auth_header = request.headers.get("authorization") or request.headers.get("Authorization")
            if provided_token:
                tok = provided_token
                if tok.lower().startswith("bearer "):
                    tok = tok.split(" ", 1)[1]
                payload = decode_access_token(tok)
                username = payload.get("sub")
                if username:
                    auth_user = db.query(models.User).filter(models.User.username == username).first()
            elif auth_header:
                tok = auth_header
                if tok.lower().startswith("bearer "):
                    tok = tok.split(" ", 1)[1]
                payload = decode_access_token(tok)
                username = payload.get("sub")
                if username:
                    auth_user = db.query(models.User).filter(models.User.username == username).first()
            # allow optional env token for dev fallback
            if not auth_user and env_token and provided_token == env_token:
                # dev fallback accepted but do not set auth_user
                pass
            else:
                if not auth_user:
                    raise HTTPException(status_code=401, detail="Not authenticated")
                require_permission(auth_user, "register_documents")
    except HTTPException:
        raise
    except Exception:
        raise HTTPException(status_code=401, detail="Not authenticated")
    try:
        safe_name = os.path.basename(tmp_name)
        if not safe_name:
            raise HTTPException(status_code=400, detail="Invalid upload name")
        # enforce allowed extension
        _, ext = os.path.splitext(safe_name.lower())
        if ext not in ALLOWED_EXTENSIONS:
            raise HTTPException(status_code=400, detail="Unsupported file extension")

        body = await request.body()
        size = len(body)
        if size == 0:
            raise HTTPException(status_code=400, detail="Empty upload")
        if size > MAX_FILE_SIZE:
            raise HTTPException(status_code=413, detail="File exceeds maximum allowed size")

        os.makedirs(TEMP_UPLOAD_DIR, exist_ok=True)
        dest_path = os.path.join(TEMP_UPLOAD_DIR, safe_name)
        with open(dest_path, "wb") as fh:
            fh.write(body)

        # if upload used upload_token flow, metadata file already exists; otherwise, create a simple meta file linking this tmp to the uploader for later validation/confirm
        meta_path = os.path.join(TEMP_UPLOAD_DIR, f"{safe_name}.meta.json")
        if not os.path.exists(meta_path):
            meta = {
                "tmp_name": safe_name,
                "original_filename": safe_name,
                "username": getattr(auth_user, "username", None),
                "upload_token": provided_upload_token or None,
                "created_at": int(time.time()),
                "expires_at": int(time.time()) + (10 * 60),
                "consumed_at": None,
                "consumed_by": None,
            }
            try:
                with open(meta_path, "w", encoding="utf-8") as mf:
                    json.dump(meta, mf)
            except Exception:
                pass
        elif provided_upload_token:
            try:
                with open(meta_path, "r", encoding="utf-8") as mf:
                    existing_meta = json.load(mf)
                existing_meta["consumed_at"] = int(time.time())
                existing_meta["consumed_by"] = getattr(auth_user, "username", None)
                existing_meta["upload_token"] = None
                with open(meta_path, "w", encoding="utf-8") as mf:
                    json.dump(existing_meta, mf)
            except Exception:
                pass

        return {"ok": True, "tmp_name": safe_name, "size": size}
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/bulk-register/validate_tmp")
def validate_bulk_register_tmp(payload: dict = Body(...), db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Validate temporary uploaded files by name (these files must exist in TEMP_UPLOAD_DIR)."""
    require_permission(current_user, "register_documents")
    tmp_names = payload.get("tmp_names") or []
    if not isinstance(tmp_names, list) or not tmp_names:
        raise HTTPException(status_code=400, detail="tmp_names list is required")

    results = []
    total = 0
    valid_count = 0
    invalid_count = 0
    for idx, tmp in enumerate(tmp_names, start=1):
        total += 1
        safe_name = os.path.basename(tmp or "")
        path = os.path.join(TEMP_UPLOAD_DIR, safe_name)
        errors = []
        if not os.path.exists(path):
            errors.append("Temporary file not found")
            invalid_count += 1
            results.append({"index": idx, "filename": safe_name, "valid": False, "errors": errors})
            continue
        try:
            size = os.path.getsize(path)
            if size == 0:
                errors.append("Empty file")
            if size > MAX_FILE_SIZE:
                errors.append("File exceeds maximum allowed size")
            _, ext = os.path.splitext(safe_name.lower())
            if ext not in ALLOWED_EXTENSIONS:
                errors.append("Unsupported file extension")

            if errors:
                invalid_count += 1
                results.append({"index": idx, "filename": safe_name, "valid": False, "errors": errors})
            else:
                valid_count += 1
                results.append({"index": idx, "filename": safe_name, "valid": True, "size": size, "tmp_name": safe_name})
        except Exception as exc:
            invalid_count += 1
            results.append({"index": idx, "filename": safe_name or f"file_{idx}", "valid": False, "errors": [str(exc)]})

    return {"total_files": total, "valid_files": valid_count, "invalid_files": invalid_count, "files": results}


@router.post("/uploads/create_tmp_uploads")
def create_tmp_uploads(payload: dict = Body(...), db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Create server-side temporary upload entries and return per-file upload URLs with short-lived upload tokens.
    Payload: {"files": [{"filename": "...", "size": 123}, ...]}
    """
    require_permission(current_user, "register_documents")
    files = payload.get("files") or []
    if not isinstance(files, list) or not files:
        raise HTTPException(status_code=400, detail="files list required")

    os.makedirs(TEMP_UPLOAD_DIR, exist_ok=True)
    results = []
    for f in files:
        filename = f.get("filename") or ""
        safe_basename = os.path.basename(filename)
        _, ext = os.path.splitext(safe_basename.lower())
        if ext not in ALLOWED_EXTENSIONS:
            results.append({"filename": filename, "ok": False, "reason": "Unsupported extension"})
            continue
        # generate tmp name and upload token
        tmp_name = f"tmp_{int(time.time())}_{secrets.token_hex(8)}_{safe_basename}"
        upload_token = uuid.uuid4().hex
        expires_at = int(time.time()) + (10 * 60)  # 10 minutes
        meta = {
            "tmp_name": tmp_name,
            "original_filename": safe_basename,
            "username": getattr(current_user, "username", None),
            "upload_token": upload_token,
            "created_at": int(time.time()),
            "expires_at": expires_at,
            "consumed_at": None,
            "consumed_by": None,
        }
        meta_path = os.path.join(TEMP_UPLOAD_DIR, f"{tmp_name}.meta.json")
        try:
            with open(meta_path, "w", encoding="utf-8") as mf:
                json.dump(meta, mf)
        except Exception as exc:
            results.append({"filename": filename, "ok": False, "reason": f"meta write error: {exc}"})
            continue

        upload_url = f"/documents/uploads/tmp/{quote(tmp_name)}?upload_token={upload_token}"
        # return full absolute URL
        full_url = f"{os.getenv('BACKEND_URL', 'http://127.0.0.1:8001').rstrip('/')}" + upload_url
        results.append({"filename": filename, "ok": True, "tmp_name": tmp_name, "upload_url": full_url, "upload_token": upload_token})

    return {"files": results}


@router.post("/bulk-register/confirm_tmp")
def confirm_bulk_register_tmp(payload: dict = Body(...), db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Confirm and create Document records from temporary uploaded files.
    Payload: {"tmp_names": [...], optional metadata fields }
    """
    require_permission(current_user, "register_documents")
    tmp_names = payload.get("tmp_names") or []
    if not isinstance(tmp_names, list) or not tmp_names:
        raise HTTPException(status_code=400, detail="tmp_names list is required")

    title = payload.get("title")
    description = payload.get("description")
    category = payload.get("category")
    document_type = payload.get("document_type")
    current_office = payload.get("current_office")
    assigned_to = payload.get("assigned_to")
    author = payload.get("author")
    priority = payload.get("priority") or "Medium"

    created = []
    failed = []

    _ensure_upload_dirs()

    for idx, tmp in enumerate(tmp_names, start=1):
        safe_name = os.path.basename(tmp or "")
        tmp_path = os.path.join(TEMP_UPLOAD_DIR, safe_name)
        if not os.path.exists(tmp_path):
            failed.append({"index": idx, "filename": safe_name, "reason": "Temporary file not found"})
            continue
        try:
            with open(tmp_path, "rb") as fh:
                content = fh.read()
            size = len(content)
            if size == 0:
                raise Exception("Empty file")
            if size > MAX_FILE_SIZE:
                raise Exception("File exceeds maximum allowed size")

            base_title = os.path.splitext(os.path.basename(safe_name))[0]
            doc_title = (title or base_title or f"Document {idx}").strip()

            # generate unique tracking number
            attempt = 0
            while True:
                attempt += 1
                tracking_number = _next_tracking_number(db)
                existing = db.query(models.Document).filter(models.Document.tracking_number == tracking_number).first()
                if not existing:
                    break
                if attempt > 5:
                    raise Exception("Unable to generate unique tracking number")

            doc = models.Document(
                tracking_number=tracking_number,
                title=doc_title,
                description=(description or None),
                category=(category or None),
                document_type=(document_type or None),
                current_office=(current_office or None),
                assigned_to=(assigned_to or None),
                author=(author or None),
                status="Pending",
                priority=(priority or "Medium") or "Medium",
                date_registered=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                qr_code_value=None,
                created_by=getattr(current_user, "username", None),
            )
            db.add(doc)
            db.commit()
            db.refresh(doc)
            payload = _compute_qr_payload(doc)
            doc.qr_code_value = payload
            db.commit()
            db.refresh(doc)
            _ensure_qr_png(doc, payload)

            # move file from tmp to uploads
            safe_stored = f"{int(datetime.now(timezone.utc).timestamp())}_{secrets.token_hex(8)}_{os.path.basename(safe_name)}"
            dest_path = os.path.join(UPLOAD_DIR, safe_stored)
            with open(dest_path, "wb") as fh:
                fh.write(content)

            att = models.Attachment(
                document_id=doc.id,
                original_filename=safe_name,
                stored_path=dest_path,
                mime_type=mimetypes.guess_type(safe_name)[0],
                size=size,
                checksum=hashlib.sha256(content).hexdigest(),
            )
            db.add(att)
            doc.attachment_name = safe_stored
            if document_type:
                doc.document_type_id = _get_or_create_by_name(db, models.DocumentType, document_type)
            if current_office:
                doc.current_office_id = _get_or_create_by_name(db, models.Office, current_office)

            db.commit()
            db.refresh(att)
            db.refresh(doc)

            created.append({"index": idx, "id": doc.id, "tracking_number": doc.tracking_number, "filename": safe_name})

            # remove tmp file
            try:
                os.remove(tmp_path)
            except Exception:
                pass
        except Exception as exc:
            try:
                db.rollback()
            except Exception:
                pass
            failed.append({"index": idx, "filename": safe_name or f"file_{idx}", "reason": str(exc)})

    # audit
    try:
        record_audit_log(
            db,
            actor=getattr(current_user, "username", None),
            action="BULK_DOCUMENT_REGISTRATION",
            target_type="Document",
            target_id=None,
            details=json.dumps({"submitted": len(tmp_names), "created": len(created), "failed": len(failed), "failures": failed}),
        )
    except Exception:
        pass

    return {"success": len(failed) == 0, "total": len(tmp_names), "registered": len(created), "failed": len(failed), "documents": created, "errors": failed}


@router.post("/bulk-register/validate")
def validate_bulk_register(files: list[UploadFile] = File(...), db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    """Validate uploaded files for bulk registration. Files are saved temporarily for inspection by the client if desired.
    This endpoint does NOT create Document records; it only validates files and stores them in a temporary location.
    """
    require_permission(current_user, "register_documents")
    os.makedirs(TEMP_UPLOAD_DIR, exist_ok=True)

    results = []
    total = 0
    valid_count = 0
    invalid_count = 0
    for idx, f in enumerate(files, start=1):
        total += 1
        filename = getattr(f, "filename", None) or ""
        content_type = getattr(f, "content_type", None)
        try:
            # read up to MAX_FILE_SIZE + 1 to detect oversize
            content = f.file.read(MAX_FILE_SIZE + 1)
            size = len(content)
            is_allowed, errors = _is_allowed_file(filename, content_type)
            if size == 0:
                errors.append("Empty file")
            if size > MAX_FILE_SIZE:
                errors.append("File exceeds maximum allowed size")
            valid = len(errors) == 0 and is_allowed
            if valid:
                valid_count += 1
                # save to temporary file for possible later confirm; name safely
                safe_name = f"tmp_{int(datetime.now(timezone.utc).timestamp())}_{secrets.token_hex(8)}_{os.path.basename(filename)}"
                tmp_path = os.path.join(TEMP_UPLOAD_DIR, safe_name)
                with open(tmp_path, "wb") as fh:
                    fh.write(content)
                results.append({"index": idx, "filename": filename, "valid": True, "size": size, "tmp_name": safe_name})
            else:
                invalid_count += 1
                results.append({"index": idx, "filename": filename, "valid": False, "errors": errors})
        except Exception as exc:
            invalid_count += 1
            results.append({"index": idx, "filename": filename or f"file_{idx}", "valid": False, "errors": [str(exc)]})
        finally:
            try:
                f.file.close()
            except Exception:
                pass

    return {"total_files": total, "valid_files": valid_count, "invalid_files": invalid_count, "files": results}


@router.post("/bulk-register/confirm")
def confirm_bulk_register(files: list[UploadFile] = File(...),
                          title: str | None = Form(None),
                          description: str | None = Form(None),
                          category: str | None = Form(None),
                          document_type: str | None = Form(None),
                          current_office: str | None = Form(None),
                          assigned_to: str | None = Form(None),
                          author: str | None = Form(None),
                          priority: str | None = Form("Medium"),
                          db: Session = Depends(get_db),
                          current_user: models.User = Depends(get_current_user)):
    """Process bulk registration: create Document records and store attachments.
    Returns per-file results and overall summary.
    """
    require_permission(current_user, "register_documents")
    _ensure_upload_dirs()

    created = []
    failed = []

    for idx, f in enumerate(files, start=1):
        filename = getattr(f, "filename", None) or ""
        content_type = getattr(f, "content_type", None)
        try:
            content = f.file.read(MAX_FILE_SIZE + 1)
            size = len(content)
            is_allowed, errors = _is_allowed_file(filename, content_type)
            if size == 0:
                errors.append("Empty file")
            if size > MAX_FILE_SIZE:
                errors.append("File exceeds maximum allowed size")
            if not is_allowed or errors:
                raise Exception("; ".join(errors))

            # attempt to create document record
            base_title = os.path.splitext(os.path.basename(filename))[0]
            doc_title = (title or base_title or f"Document {idx}").strip()

            # generate a tracking number and ensure uniqueness by retrying on conflict
            attempt = 0
            while True:
                attempt += 1
                tracking_number = _next_tracking_number(db)
                existing = db.query(models.Document).filter(models.Document.tracking_number == tracking_number).first()
                if not existing:
                    break
                if attempt > 5:
                    raise Exception("Unable to generate unique tracking number")

            doc = models.Document(
                tracking_number=tracking_number,
                title=doc_title,
                description=(description or None),
                category=(category or None),
                document_type=(document_type or None),
                current_office=(current_office or None),
                assigned_to=(assigned_to or None),
                author=(author or None),
                status="Pending",
                priority=(priority or "Medium") or "Medium",
                date_registered=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                qr_code_value=tracking_number,
                created_by=getattr(current_user, "username", None),
            )
            db.add(doc)
            db.commit()
            db.refresh(doc)

            # save file to uploads dir
            safe_name = f"{int(datetime.now(timezone.utc).timestamp())}_{secrets.token_hex(8)}_{os.path.basename(filename)}"
            dest_path = os.path.join(UPLOAD_DIR, safe_name)
            with open(dest_path, "wb") as fh:
                fh.write(content)

            # create attachment row
            att = models.Attachment(
                document_id=doc.id,
                original_filename=filename,
                stored_path=dest_path,
                mime_type=content_type or mimetypes.guess_type(filename)[0],
                size=size,
                checksum=hashlib.sha256(content).hexdigest(),
            )
            db.add(att)
            doc.attachment_name = safe_name
            if document_type:
                doc.document_type_id = _get_or_create_by_name(db, models.DocumentType, document_type)
            if current_office:
                doc.current_office_id = _get_or_create_by_name(db, models.Office, current_office)

            db.commit()
            db.refresh(att)
            db.refresh(doc)

            created.append({"index": idx, "id": doc.id, "tracking_number": doc.tracking_number, "filename": filename})
        except Exception as exc:
            try:
                db.rollback()
            except Exception:
                pass
            failed.append({"index": idx, "filename": filename or f"file_{idx}", "reason": str(exc)})
        finally:
            try:
                f.file.close()
            except Exception:
                pass

    # record audit log for the bulk operation
    try:
        record_audit_log(
            db,
            actor=getattr(current_user, "username", None),
            action="BULK_DOCUMENT_REGISTRATION",
            target_type="Document",
            target_id=None,
            details=json.dumps({"submitted": len(files), "created": len(created), "failed": len(failed), "failures": failed}),
        )
    except Exception:
        pass

    return {"success": len(failed) == 0, "total": len(files), "registered": len(created), "failed": len(failed), "documents": created, "errors": failed}


def _next_tracking_number(db: Session) -> str:
    rows = db.query(models.Document.tracking_number).filter(models.Document.tracking_number.like("DOC-%")).all()
    used_numbers = set()
    for (tracking_number,) in rows:
        if not tracking_number or not tracking_number.startswith("DOC-"):
            continue
        suffix = tracking_number.replace("DOC-", "", 1)
        if suffix.isdigit():
            used_numbers.add(int(suffix))

    candidate = 1
    while candidate in used_numbers:
        candidate += 1
    return f"DOC-{candidate}"


def _serialize_document(doc: models.Document):
    payload = {
        "id": doc.id,
        "tracking_number": doc.tracking_number,
        "title": doc.title,
        "description": doc.description,
        "document_type": doc.document_type,
        "category": doc.category,
        "originating_office": doc.originating_office,
        "current_office": doc.current_office,
        "assigned_to": doc.assigned_to,
        "status": doc.status,
        "priority": doc.priority,
        "remarks": doc.remarks,
        "author": doc.author,
        "session": doc.session,
        "date_registered": doc.date_registered,
        "attachment_name": doc.attachment_name,
        "qr_code_value": doc.qr_code_value,
        "created_by": doc.created_by,
        "created_by_id": getattr(doc, "created_by_id", None),
        "document_type_id": getattr(doc, "document_type_id", None),
        "category_id": getattr(doc, "category_id", None),
        "originating_office_id": getattr(doc, "originating_office_id", None),
        "current_office_id": getattr(doc, "current_office_id", None),
        "archived": bool(doc.archived),
        "archived_at": doc.archived_at,
        "archived_by": doc.archived_by,
        "date_archived": doc.archived_at.isoformat() if doc.archived_at else None,
        "created_at": doc.created_at,
        "updated_at": doc.updated_at,
    }
    # include normalized history rows
    try:
        hist_rows = db_session = None
        from ..database import SessionLocal
        db_session = SessionLocal()
        rows = (
            db_session.query(models.DocumentHistory)
            .filter(models.DocumentHistory.document_id == doc.id)
            .order_by(models.DocumentHistory.created_at.asc())
            .all()
        )
        payload["history_rows"] = [
            {
                "id": r.id,
                "action": r.action,
                "actor": r.actor,
                "from_office": r.from_office,
                "to_office": r.to_office,
                "notes": r.notes,
                "created_at": r.created_at,
            }
            for r in rows
        ]
    except Exception:
        payload["history_rows"] = []
    finally:
        try:
            if db_session:
                db_session.close()
        except Exception:
            pass
    # include attachments metadata (stored_path hidden for security)
    try:
        db_session = SessionLocal()
        atts = db_session.query(models.Attachment).filter(models.Attachment.document_id == doc.id).all()
        payload["attachments"] = [
            {"id": a.id, "original_filename": a.original_filename, "mime_type": a.mime_type, "size": a.size, "checksum": a.checksum} for a in atts
        ]
    except Exception:
        payload["attachments"] = []
    finally:
        try:
            if db_session:
                db_session.close()
        except Exception:
            pass
    return payload


def _find_document_by_qr_or_tracking(db: Session, qr_value: str):
    if not qr_value:
        return None
    qr_text = str(qr_value).strip()
    if not qr_text:
        return None
    normalized_tracking = _normalize_tracking_query(qr_text)
    candidate_value = qr_text
    query = db.query(models.Document)
    if normalized_tracking is not None:
        canonical_tracking = f"DOC-{int(normalized_tracking)}"
        query = query.filter(
            or_(
                models.Document.qr_code_value == candidate_value,
                models.Document.qr_code_value == canonical_tracking,
                models.Document.tracking_number == canonical_tracking,
                models.Document.tracking_number == qr_text.upper(),
            )
        )
    else:
        query = query.filter(
            or_(
                models.Document.qr_code_value == candidate_value,
                models.Document.qr_code_value == qr_text.upper(),
                models.Document.tracking_number == qr_text.upper(),
            )
        )
    return query.first()


def _compute_qr_payload(doc: models.Document) -> str:
    backend_url = os.getenv("BACKEND_URL") or os.getenv("PUBLIC_BACKEND_URL") or os.getenv("API_BASE_URL") or "http://127.0.0.1:8001"
    backend_url = backend_url.rstrip("/")
    tracking = (doc.tracking_number or "").strip()
    if not tracking:
        tracking = f"DOC-{doc.id}"
    return f"{backend_url}/documents/qr/{quote(str(tracking), safe='')}"


def _qr_image_path_for_document(doc: models.Document) -> str:
    os.makedirs(QR_IMAGE_DIR, exist_ok=True)
    safe_tracking = (doc.tracking_number or f"DOC-{doc.id}").strip().replace(os.sep, "_").replace("/", "_")
    return os.path.join(QR_IMAGE_DIR, f"{safe_tracking}.png")


def _ensure_qr_png(doc: models.Document, payload: str | None = None) -> str:
    payload = payload or _compute_qr_payload(doc)
    image_path = _qr_image_path_for_document(doc)
    os.makedirs(QR_IMAGE_DIR, exist_ok=True)
    try:
        if not os.path.exists(image_path):
            qr_img = qrcode.make(payload)
            qr_img.save(image_path, format="PNG")
    except Exception:
        raise HTTPException(status_code=500, detail="Unable to generate the QR PNG image")
    return image_path


def _render_qr_label_pdf(documents: list[models.Document]):
    buffer = io.BytesIO()
    page_width, page_height = letter

    # The chosen QR label density is a compact, scan-friendly 4 x 6 page layout.
    # It prevents the QR from consuming too much page area while still leaving
    # enough room for the metadata below it.
    margin = 24
    columns = 4
    rows = 6

    label_width = (page_width - (margin * 2)) / columns
    label_height = (page_height - (margin * 2)) / rows

    # Keep the QR code in a forgiving size range for standard printer output.
    qr_side = min(52, label_width - 24, (label_height * 0.48))
    if qr_side < 40:
        qr_side = 40

    pdf = canvas.Canvas(buffer, pagesize=letter)

    for index, doc in enumerate(documents):
        if index > 0 and index % (columns * rows) == 0:
            pdf.showPage()

        local_index = index % (columns * rows)
        col = local_index % columns
        row_from_top = local_index // columns

        label_left = margin + col * label_width
        label_bottom = page_height - margin - (row_from_top + 1) * label_height

        qr_x = label_left + (label_width - qr_side) / 2
        qr_y = label_bottom + label_height - 24 - qr_side

        # Draw QR in the upper part of the label cell so the metadata is below it.
        value = doc.qr_code_value or doc.tracking_number or f"DOC-{doc.id}"
        qr_img = qrcode.make(str(value))
        qr_buffer = io.BytesIO()
        qr_img.save(qr_buffer, format="PNG")
        qr_buffer.seek(0)
        image = ImageReader(qr_buffer)

        pdf.drawImage(
            image,
            qr_x,
            qr_y,
            width=qr_side,
            height=qr_side,
            mask="auto",
        )

        text_y = label_bottom + 12
        pdf.setFont("Helvetica-Bold", 8)
        pdf.drawString(label_left + 8, text_y, f"{doc.tracking_number or 'No tracking'}")

        text_y += 13
        pdf.setFont("Helvetica", 7)
        title = (doc.title or "Untitled")[:38]
        pdf.drawString(label_left + 8, text_y, title)

        text_y += 12
        office = doc.current_office or "No location"
        pdf.drawString(label_left + 8, text_y, office)

    pdf.save()
    buffer.seek(0)
    return buffer


def _get_history_event_timestamp(item: dict):
    if item is None:
        return ""
    if item.get("created_at"):
        return str(item.get("created_at"))
    if item.get("date") and item.get("time"):
        return f"{item.get('date')} {item.get('time')}"
    if item.get("date"):
        return item.get("date")
    return ""


def _get_or_create_by_name(db: Session, Model, name: str):
    if not name:
        return None
    name = name.strip()
    existing = db.query(Model).filter(Model.name == name).first()
    if existing:
        return existing.id
    try:
        obj = Model(name=name)
        db.add(obj)
        db.commit()
        db.refresh(obj)
        return obj.id
    except exc.IntegrityError:
        db.rollback()
        existing = db.query(Model).filter(Model.name == name).first()
        return existing.id if existing else None


def _normalize_tracking_query(search: str | None) -> str | None:
    if search is None:
        return None
    text = str(search).strip()
    if not text:
        return None
    match = re.fullmatch(r"(?i)(?:doc[-\s]*)?0*([1-9][0-9]*|0)", text)
    if match:
        return match.group(1)
    return None


@router.get("", response_model=list[schemas.DocumentResponse])
def list_documents(
    search: str | None = Query(default=None),
    status: str | None = None,
    document_type: str | None = None,
    category: str | None = None,
    current_office: str | None = None,
    year: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    priority: str | None = None,
    archived: bool | None = Query(default=None),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    require_permission(current_user, "view_documents")
    query = db.query(models.Document)
    if archived is not None:
        query = query.filter(models.Document.archived.is_(archived))
    else:
        query = query.filter(models.Document.archived.is_(False))
    if search:
        normalized_tracking = _normalize_tracking_query(search)
        if normalized_tracking is not None and re.fullmatch(r"(?i)(?:doc[-\s]*)?0*([1-9][0-9]*|0)", str(search).strip()):
            canonical_tracking = f"DOC-{int(normalized_tracking)}"
            query = query.filter(
                or_(
                    models.Document.tracking_number == canonical_tracking,
                    models.Document.tracking_number == str(search).strip().upper(),
                )
            )
        else:
            like = f"%{search.lower()}%"
            query = query.filter(
                or_(
                    models.Document.tracking_number.ilike(like),
                    models.Document.title.ilike(like),
                    models.Document.description.ilike(like),
                    models.Document.document_type.ilike(like),
                    models.Document.category.ilike(like),
                    models.Document.originating_office.ilike(like),
                    models.Document.current_office.ilike(like),
                    models.Document.assigned_to.ilike(like),
                    models.Document.status.ilike(like),
                    models.Document.remarks.ilike(like),
                    models.Document.author.ilike(like),
                    models.Document.session.ilike(like),
                    models.Document.created_by.ilike(like),
                )
            )
    if status:
        query = query.filter(models.Document.status == status)
    if document_type:
        query = query.filter(models.Document.document_type == document_type)
    if category:
        query = query.filter(models.Document.category == category)
    if current_office:
        query = query.filter(models.Document.current_office == current_office)
    if priority:
        query = query.filter(models.Document.priority == priority)
    if year:
        year_text = str(year).strip()
        if year_text.isdigit() and len(year_text) == 4:
            start_year = datetime(int(year_text), 1, 1, tzinfo=timezone.utc)
            end_year = datetime(int(year_text) + 1, 1, 1, tzinfo=timezone.utc)
            query = query.filter(models.Document.created_at >= start_year, models.Document.created_at < end_year)
    if start_date:
        query = query.filter(models.Document.created_at >= start_date)
    if end_date:
        query = query.filter(models.Document.created_at <= end_date)

    docs = query.order_by(models.Document.created_at.desc()).all()
    return [_serialize_document(doc) for doc in docs]




@router.get("/{document_id:int}", response_model=schemas.DocumentResponse)
def get_document(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "view_document_details")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    return _serialize_document(doc)


@router.put("/{document_id:int}", response_model=schemas.DocumentResponse)
def update_document(document_id: int, payload: schemas.DocumentUpdate, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "edit_documents")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    if payload.tracking_number is not None and payload.tracking_number != doc.tracking_number:
        existing = db.query(models.Document).filter(models.Document.tracking_number == payload.tracking_number).first()
        if existing:
            raise HTTPException(status_code=409, detail="Tracking number already exists")

    data = payload.model_dump(exclude_unset=True)
    # apply simple fields
    for field, value in data.items():
        if field in ("document_type", "category", "originating_office", "current_office"):
            # handled below to populate normalized FK columns
            continue
        setattr(doc, field, value)

    # handle normalized lookups
    if data.get("document_type") is not None:
        doc.document_type = data.get("document_type")
        doc.document_type_id = _get_or_create_by_name(db, models.DocumentType, data.get("document_type"))
    if data.get("category") is not None:
        doc.category = data.get("category")
        doc.category_id = _get_or_create_by_name(db, models.Category, data.get("category"))
    if data.get("originating_office") is not None:
        doc.originating_office = data.get("originating_office")
        doc.originating_office_id = _get_or_create_by_name(db, models.Office, data.get("originating_office"))
    if data.get("current_office") is not None:
        doc.current_office = data.get("current_office")
        doc.current_office_id = _get_or_create_by_name(db, models.Office, data.get("current_office"))

    db.commit()
    db.refresh(doc)
    return _serialize_document(doc)


@router.post("/register", response_model=schemas.DocumentResponse)
def register_document(
    title: str = Form(...),
    description: Optional[str] = Form(None),
    category: Optional[str] = Form(None),
    document_type: Optional[str] = Form(None),
    current_office: Optional[str] = Form(None),
    assigned_to: Optional[str] = Form(None),
    author: Optional[str] = Form(None),
    priority: Optional[str] = Form("Medium"),
    tracking_number: Optional[str] = Form(None),
    file: UploadFile | None = File(None),
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    require_permission(current_user, "register_documents")

    title = (title or "").strip()
    if not title:
        raise HTTPException(status_code=400, detail="Title is required")

    tracking_number = (tracking_number or "").strip()
    if tracking_number:
        existing = db.query(models.Document).filter(models.Document.tracking_number == tracking_number).first()
        if existing:
            raise HTTPException(status_code=409, detail="Tracking number already exists")
    else:
        tracking_number = _next_tracking_number(db)

    category = (category or None)
    document_type = (document_type or None)
    current_office = (current_office or None)
    assigned_to = (assigned_to or None)
    author = (author or None)
    priority = (priority or "Medium") or "Medium"

    doc = models.Document(
        tracking_number=tracking_number,
        title=title,
        description=(description or None),
        category=category,
        document_type=document_type,
        current_office=current_office,
        assigned_to=assigned_to,
        author=author,
        status="Pending",
        priority=priority,
        date_registered=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        qr_code_value=None,
        created_by=getattr(current_user, "username", None),
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    payload = _compute_qr_payload(doc)
    doc.qr_code_value = payload
    db.commit()
    db.refresh(doc)
    _ensure_qr_png(doc, payload)

    # handle optional file upload and persist attachment metadata
    if file is not None:
        try:
            os.makedirs(UPLOAD_DIR, exist_ok=True)
            content = file.file.read()
            checksum = hashlib.sha256(content).hexdigest()
            safe_name = f"{int(datetime.now(timezone.utc).timestamp())}_{secrets.token_hex(8)}_{os.path.basename(file.filename)}"
            dest_path = os.path.join(UPLOAD_DIR, safe_name)
            with open(dest_path, "wb") as fh:
                fh.write(content)
            # set attachment name on document and create attachment row
            doc.attachment_name = safe_name
            att = models.Attachment(
                document_id=doc.id,
                original_filename=file.filename,
                stored_path=dest_path,
                mime_type=file.content_type or mimetypes.guess_type(file.filename)[0],
                size=len(content),
                checksum=checksum,
            )
            db.add(att)
            db.commit()
            db.refresh(att)
        except Exception as exc:
            db.rollback()
            raise HTTPException(status_code=500, detail=f"Failed to save uploaded file: {exc}")

    if document_type:
        doc.document_type_id = _get_or_create_by_name(db, models.DocumentType, document_type)
    if current_office:
        doc.current_office_id = _get_or_create_by_name(db, models.Office, current_office)

    db.commit()
    db.refresh(doc)
    return _serialize_document(doc)


@router.post("/{document_id:int}/qr")
def regenerate_qr(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "generate_qr_codes")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    payload = _compute_qr_payload(doc)
    _ensure_qr_png(doc, payload)
    doc.qr_code_value = payload
    db.commit()
    db.refresh(doc)

    record_audit_log(
        db,
        actor=getattr(current_user, "username", "System"),
        action="QR_GENERATED",
        target_type="document",
        target_id=str(doc.id),
        details=f"Generated QR payload for {doc.tracking_number}",
    )

    return {
        "document_id": doc.id,
        "tracking_number": doc.tracking_number,
        "qr_payload": payload,
        "qr_image_url": f"/documents/{doc.id}/qr-image",
        "status": "generated",
    }




@router.get("/{document_id:int}/qr-image")
def get_document_qr_image(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "view_qr_tracking")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    payload = doc.qr_code_value or _compute_qr_payload(doc)
    image_path = _ensure_qr_png(doc, payload)
    if not os.path.exists(image_path):
        raise HTTPException(status_code=404, detail="QR image not found")

    return FileResponse(image_path, media_type="image/png")


@router.get("/qr/monitor")
def monitor_qr(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "view_qr_tracking")
    total_documents = db.query(models.Document).filter(models.Document.archived.is_(False)).count()
    successful_scans = db.query(models.AuditLog).filter(models.AuditLog.action == "QR_SCAN_SUCCESS").count()
    unrecognized_scans = db.query(models.AuditLog).filter(models.AuditLog.action == "QR_SCAN_UNRECOGNIZED").count()
    latest_scan_log = (
        db.query(models.AuditLog)
        .filter(models.AuditLog.action.in_(["QR_SCAN_SUCCESS", "QR_SCAN_UNRECOGNIZED"]))
        .order_by(models.AuditLog.created_at.desc())
        .first()
    )
    latest_scan = {
        "actor": latest_scan_log.actor,
        "action": latest_scan_log.action,
        "target_id": latest_scan_log.target_id,
        "details": latest_scan_log.details,
        "created_at": latest_scan_log.created_at.isoformat() if latest_scan_log and latest_scan_log.created_at else None,
    } if latest_scan_log else None

    documents = db.query(models.Document).filter(models.Document.archived.is_(False)).order_by(models.Document.updated_at.desc()).limit(100).all()
    documents_summary = [
        {
            "id": doc.id,
            "tracking_number": doc.tracking_number,
            "qr_code_value": doc.qr_code_value,
            "status": doc.status,
            "current_office": doc.current_office,
            "last_updated": doc.updated_at.isoformat() if doc.updated_at else None,
        }
        for doc in documents
    ]

    recent_generated_qrs = (
        db.query(models.Document)
        .filter(models.Document.archived.is_(False))
        .filter(models.Document.qr_code_value.isnot(None))
        .order_by(models.Document.created_at.desc())
        .limit(10)
        .all()
    )
    recent_generated_summary = [
        {
            "id": doc.id,
            "tracking_number": doc.tracking_number,
            "qr_code_value": doc.qr_code_value,
            "title": doc.title,
            "document_type": doc.document_type,
            "current_office": doc.current_office,
            "created_at": doc.created_at.isoformat() if doc.created_at else None,
        }
        for doc in recent_generated_qrs
    ]

    return {
        "total_documents": total_documents,
        "successful_scans": successful_scans,
        "unrecognized_scans": unrecognized_scans,
        "latest_scan": latest_scan,
        "documents": documents_summary,
        "recent_generated_qrs": recent_generated_summary,
    }


@router.get("/qr/{qr_value:path}")
def lookup_qr_by_value(qr_value: str, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "view_qr_tracking")

    if qr_value.strip().lower() == "monitor":
        return monitor_qr(db=db, current_user=current_user)

    doc = _find_document_by_qr_or_tracking(db, qr_value)
    if not doc:
        record_audit_log(
            db,
            actor=getattr(current_user, "username", "System"),
            action="QR_SCAN_UNRECOGNIZED",
            target_type="qr_lookup",
            target_id=str(qr_value),
            details="QR identifier was not matched to a document",
        )
        raise HTTPException(status_code=404, detail="QR code not recognized")

    record_audit_log(
        db,
        actor=getattr(current_user, "username", "System"),
        action="QR_SCAN_SUCCESS",
        target_type="document",
        target_id=str(doc.id),
        details=f"QR lookup resolved to {doc.tracking_number}",
    )

    return {
        "document_id": doc.id,
        "tracking_number": doc.tracking_number,
        "title": doc.title,
        "document_type": doc.document_type,
        "current_office": doc.current_office,
        "qr_payload": doc.qr_code_value,
    }


@router.get("/qr/labels")
def generate_qr_labels(ids: str | None = Query(default=None), db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "print_qr_codes")
    query = db.query(models.Document).filter(models.Document.archived.is_(False))
    if ids:
        id_list = [int(item.strip()) for item in str(ids).split(",") if item.strip().isdigit()]
        if id_list:
            query = query.filter(models.Document.id.in_(id_list))
    documents = query.order_by(models.Document.id.asc()).all()
    if not documents:
        raise HTTPException(status_code=404, detail="No documents found for QR label generation")
    pdf_buffer = _render_qr_label_pdf(documents)
    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=qr_labels.pdf"},
    )


@router.delete("/{document_id:int}")
def delete_document(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "archive_documents")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    doc.archived = True
    doc.archived_at = datetime.now(timezone.utc)
    doc.archived_by = getattr(current_user, "username", None)
    db.commit()
    record_audit_log(
        db,
        actor=getattr(current_user, "username", "System"),
        action="ARCHIVE_DOCUMENT",
        target_type="document",
        target_id=str(doc.id),
        details=f"Archived document {doc.tracking_number}: {doc.title}",
    )
    return {"message": "Document archived successfully"}


@router.post("/{document_id:int}/restore")
def restore_document(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "restore_documents")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    doc.archived = False
    doc.archived_at = None
    doc.archived_by = None
    db.commit()
    record_audit_log(
        db,
        actor=getattr(current_user, "username", "System"),
        action="RESTORE_ARCHIVED_DOCUMENT",
        target_type="document",
        target_id=str(doc.id),
        details=f"Restored archived document {doc.tracking_number}: {doc.title}",
    )
    return {"message": "Document restored successfully"}


@router.delete("/{document_id:int}/permanent")
def permanently_delete_document(document_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "delete_documents")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    tracking_number = doc.tracking_number
    title = doc.title
    attachments = db.query(models.Attachment).filter(models.Attachment.document_id == doc.id).all()
    for attachment in attachments:
        try:
            if attachment.stored_path and os.path.exists(attachment.stored_path):
                os.remove(attachment.stored_path)
        except Exception:
            pass
        db.delete(attachment)

    db.delete(doc)
    db.commit()
    record_audit_log(
        db,
        actor=getattr(current_user, "username", "System"),
        action="PERMANENT_DELETE_ARCHIVED_DOCUMENT",
        target_type="document",
        target_id=str(document_id),
        details=f"Permanently deleted archived document {tracking_number}: {title}",
    )
    return {"message": "Archived document permanently deleted."}


@router.get("/{document_id:int}/attachments/{attachment_id:int}")
def download_attachment(document_id: int, attachment_id: int, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "download_documents")
    doc = db.query(models.Document).filter(models.Document.id == document_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    attachment = db.query(models.Attachment).filter(models.Attachment.id == attachment_id, models.Attachment.document_id == document_id).first()
    if not attachment:
        raise HTTPException(status_code=404, detail="Attachment not found")

    if not attachment.stored_path or not os.path.isabs(attachment.stored_path):
        raise HTTPException(status_code=500, detail="Invalid attachment path")
    if not os.path.exists(attachment.stored_path):
        raise HTTPException(status_code=404, detail="Attachment file not found")

    return FileResponse(
        attachment.stored_path,
        filename=attachment.original_filename,
        media_type=attachment.mime_type or "application/octet-stream",
    )


@router.get("/template")
def download_import_template(db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    require_permission(current_user, "import_documents")
    try:
        import openpyxl
    except Exception:
        raise HTTPException(status_code=500, detail="Server missing openpyxl for template generation")

    try:
        wb = openpyxl.Workbook()
        ws = wb.active
        headers = [
            "Tracking Number",
            "Title",
            "Document Type",
            "Category",
            "Description",
            "Origin Office",
            "Current Office",
            "Current Holder",
            "Status",
            "Author",
            "Session",
            "Date Registered",
            "Remarks",
        ]
        ws.append(headers)
        stream = io.BytesIO()
        wb.save(stream)
        stream.seek(0)
        return StreamingResponse(
            stream,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=documents_import_template.xlsx"},
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


def _parse_rows_from_file(file: UploadFile) -> list[dict]:
    name = (file.filename or "").lower()
    content = file.file.read()
    rows = []
    if name.endswith(".csv") or name.endswith(".txt"):
        text = content.decode("utf-8-sig")
        reader = csv.DictReader(io.StringIO(text))
        for r in reader:
            rows.append(r)
    else:
        try:
            import openpyxl
        except Exception:
            raise HTTPException(status_code=500, detail="Server missing openpyxl for xlsx parsing")
        wb = openpyxl.load_workbook(filename=io.BytesIO(content), data_only=True)
        ws = wb.active
        header = None
        for idx, row in enumerate(ws.iter_rows(values_only=True), start=1):
            if idx == 1:
                header = [str(c).strip() if c is not None else "" for c in row]
                continue
            if not header:
                continue
            data = {}
            empty = True
            for h, cell in zip(header, row):
                if cell is not None and str(cell).strip() != "":
                    empty = False
                data[h or ""] = str(cell).strip() if cell is not None else ""
            if empty:
                continue
            rows.append(data)
    return rows


# Legacy import preview endpoint removed: import-by-file workflow deprecated


def _ensure_upload_dirs():
    os.makedirs(UPLOAD_DIR, exist_ok=True)


# Removed separate upload page — uploads are handled inline via the admin frontend FilePicker


# Legacy import endpoints removed: import-by-file and temp upload workflow deprecated
